README.md
| Branch?           | develop
| Description?      | Add Modules required in doc.
| BC breaks?        | N/A 
| Deprecations?     | N/A
| Fixed ticket?     | Fixes https://github.com/Oksydan/modern-prestashop-starter-theme/issues/17
=> Add Modules required

LICENSE.md, README.md
Docs update.
Lowering node.js version requirements.
=> Version 1.0.1 changes

modules/ps_emailalerts/js/index.php, modules/ps_emailalerts/js/mailalerts.js, modules/ps_emailalerts/views/templates/front/index.php, modules/ps_emailalerts/views/templates/front/mailalerts-account-line.tpl, modules/ps_emailalerts/views/templates/front/mailalerts-account.tpl, modules/ps_emailalerts/views/templates/hook/product-modal.tpl, modules/ps_emailalerts/views/templates/hook/product.tpl
Related issue: https://github.com/Oksydan/modern-prestashop-starter-theme/issues/25
=> ps_emailalerts improvements and theme adjustments

_dev/css/abstracts/_index.scss, _dev/css/abstracts/mixins/_hf.scss, _dev/css/abstracts/mixins/_index.scss, _dev/css/listing/components/listing-display/_display-toggle.scss, _dev/css/theme/components/customer/_address.scss, _dev/css/theme/components/customer/_customer-links.scss, _dev/css/theme/components/links-list/_links-list.scss, _dev/css/theme/components/menu/_mainmenu.scss, _dev/css/theme/layout/_header.scss, _dev/css/theme/override/bootstrap-touchspin/_bootstrap-touchspin.scss, _dev/css/theme/override/bootstrap/_collapse.scss, _dev/js/components/PageSlider.js, _dev/package.json, _dev/preload-template.html, _dev/webpack/webpack.parts.js, _dev/webpack/webpack.production.js, config/theme.yml, templates/_partials/header.tpl, templates/catalog/_partials/per-page.tpl, templates/catalog/_partials/products-top.tpl, templates/checkout/_partials/header.tpl
=> New version 1.2.1

templates/errors/maintenance.tpl
=> Fix shop logo url in maintenance.tpl

README.md
I've seen some things to improve in the docs, this is part 1 of the improvements.
=> Docs update part 1

modules/ps_emailalerts/views/templates/hook/my-account-footer.tpl
| Description?      | Add some class to have the same style with other link in the footer.
| Fixed ticket?     | #165
=> fix style my-account-footer.tpl

templates/checkout/_partials/address-selector-block.tpl
| Description?      | The icons are duplicate on edit and delete actions.
| Fixed ticket?     | #170
=> Fix duplicate icons on address

_dev/js/product/index.js
| Description?      | Fixing product details tab bug. Details hidden when combination/quantity changing with details displayed.
| Fixed ticket?     | Issue [link](https://github.com/Oksydan/falcon/issues/167)
=> Product details tab fix

_dev/js/theme/components/usePasswordPolicy.js
| Description?      | Multiple password policy fix
| Fixed ticket?     | nope, quick fix
=> Multiple password policy inputs fix

README.md
| Description?      | Please describe your changes as much as possible.
| Type?             | bug fix / improvement / new feature / refacto
| Fixed ticket?     | Issue link here
=> Sponsors update

README.md
| Description?      | Please describe your changes as much as possible.
| Type?             | bug fix / improvement / new feature / refacto
| Fixed ticket?     | Issue link here
=> Readme sponsors logo update

README.md
| Description?      | Please describe your changes as much as possible.
| Type?             | bug fix / improvement / new feature / refacto
| Fixed ticket?     | Issue link here
=> Readme sponsor support for light/dark GH theme

_dev/css/theme/components/search/_search-form.scss, _dev/css/theme/components/search/_search-result.scss
| Description?      | The search result ajax is not showing correctly between 720px and 960px.
| Fixed ticket?     | #178
=> Search result ajax responsive bug

_dev/js/theme/components/cart/cart.js, _dev/js/theme/components/selectors.js
| Description?      | The update JS on cart page not working completely
| Fixed ticket?     | #182
=> Fix cart update quantity unavalaible

_dev/css/theme/vendors/_swiper.scss, _dev/js/theme/components/sliders/SwiperSlider.js, _dev/package-lock.json, _dev/package.json, _dev/yarn.lock
| Description?      | Upgrade swiper to version 9
| Type?             | improvement
| Fixed ticket?     |
=> Upgrade swiper to version 9

_dev/js/theme/components/form.js
| Description?      | Input value trim on field blur.
| Type?             |  improvement 
| Fixed ticket?     | #145
=> Form UX improvements

Makefile, _dev/webpack/.env-example
| Description?      | A Makefile has been added to reduce the time it takes to create a release package and make releases more fault-tolerant.
| Type?             | improvement 
| Fixed ticket?     | NONE
=> Makefile added to simplify release process

config/theme.yml
| Description?      | Use the SemVer about compatibility version.
| Type?             | improvement
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/220
=> Set compatibility as SemVer

_dev/js/theme/index.js, _dev/package-lock.json, _dev/package.json, _dev/yarn.lock
| Description?      | Adding feedback to user when file is being uploaded using input type file.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/211
=> Custom file input - fix to uploaded file information

README.md, _dev/package-lock.json, _dev/package.json, config/theme.yml
| Description?      | New version release 3.1.1
| Type?             | release
=> New version 3.1.1

README.md
| Description?      | Fixing wrong information about is_favoriteproducts module compatibility with Falcon theme.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/232
=> is_favoriteproducts docs fixes

templates/catalog/_partials/product-images-modal.tpl
| Description?      | Product modal multiple fixes - no image, proper order of images.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/245
=> Product images modal multiple fixes

modules/productcomments/views/js/productListingComments.js
| Description?      | Fixing product comments rating not being updated in product miniatures after listing being updated via pagination, filters, sorting. 
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/252
=> Products comments listing fix

modules/productcomments/views/js/list-comments.js, modules/productcomments/views/templates/hook/post-comment-modal.tpl
| Description?      | Fixing problem with rating update on product page cause other products to display wrong rating.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/253
=> Productcomments module product page fixes

templates/checkout/_partials/steps/payment.tpl
| Description?      | Added missing id for payment-option element to make it compatible with classic theme.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/260
=> Added missing id to payment option

_dev/js/checkout/index.js, templates/checkout/_partials/steps/shipping.tpl
| Description?      | Carrier option in checkout extra content display fix upon selection.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/270
=> Checkout carrier option extra content display fix

_dev/js/theme/core/address/handler/changeAddressCountryHandler.js
| Description?      | Fix to updating address form fields.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/157
=> address update fix

_dev/webpack/webpack.development.js, _dev/webpack/webpack.parts.js
| Description?      | Rich scss source maps added 
| Type?             |  improvement
| Fixed ticket?     | N/A
=> scss source maps fix

_dev/js/theme/core/cart/handler/cart/addToCartHandler.js, templates/catalog/_partials/miniatures/_partials/product-form.tpl
| Description?      | Bug fix related to theme core refacto
| Fixed ticket?     | N/A
=> Add to cart fix

.github/workflows/code-build-nightly-workflow.yml, .github/workflows/code-build-workflow.yml
| Description?      | Adding node 19 and 20 to node version matrix for test build workflow.
| Type?             |  improvement
| Fixed ticket?     | N/A
=> Build workflow changes

templates/catalog/_partials/product-cover-thumbnails.tpl, templates/catalog/_partials/product-images-modal.tpl
| Description?      | Fixed conditions logic responsible for displaying product images alternative text.
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/285
=> Product images - display proper alt for image

templates/customer/order-detail.tpl
| Description?      | Fixed not closed div tag in order-details.tpl. 
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/275
=> Order detail closing tag fix

config/theme.yml, templates/contact.tpl
| Description?      | Fixing wrong layout classes for contact page columns. Moving widget usage to hooks.
| Type?             | bug fix, improvement
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/281
=> theme contact page minor fixes

_dev/css/theme/override/bootstrap/_form.scss, modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl, templates/catalog/_partials/product-variants.tpl
| Description?      | Created new form-check-color for bootstrap 5 to display radio/checkbox as color selection. Minor faceted search template refactoring. 
| Type?             | bug
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/286
=> Custom form color, minor faceted search template refactoring 

templates/catalog/_partials/product-tabs.tpl, templates/catalog/_partials/product-variants.tpl
| Description?      | Minor accessibility fixes for product page
| Type?             | improvement 
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/325
The result after applying fixes
=> Product page accessibility

_dev/js/utils/dynamicImports/useBootstrapComponentDynamicImport.js
| Description?      | Minor fixes to lazy loading of Bootstrap 5 components
| Fixed ticket?     | N/A
=> Bootstrap components dynamic loading fixes

templates/catalog/_partials/miniatures/_partials/product-thumb.tpl
| Description?      | We are adding new hook for listing to allow is_favoriteproducts to use it. 
| Type?             | new feature
| Fixed ticket?     | https://github.com/Oksydan/falcon/issues/323
=> New favorite product hook for listing

README.md
| Description?      | New sponsor
=> New sponsor
